services:
  db:
    image: pgvector/pgvector:0.8.6-pg18-trixie
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?переменная не задана}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '127.0.0.1:5433:5432'
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
  storage:
    image: rustfs/rustfs:1.0.0
    environment: 
      - RUSTFS_ACCESS_KEY=${RUSTFS_ACCESS_KEY}
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY:?переменная не задана}
    ports: 
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    volumes:
      - storage-data:/data
      - storage-logs:/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -sS -o /dev/null http://127.0.0.1:9000/"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
volumes:
  db-data:
  storage-data:
  storage-logs:
